version: '3.8'

services:
  backend:
    image: azmd801/written-number-classifier-frontend:latest 
    ports:
      - "8080:8080"
    networks:
      - app-network

  streamlit:
    image: azmd801/written-number-classifier-backend:latest
    ports:
      - "8501:8501"
    environment:
      - FASTAPI_URL=http://backend:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

